name: benchmark

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8

    - name: build
      run: mvn -B package

    - name: prepare test
      run: bash bench/prepare.sh
    - name: run bench
      run: bash bench/run.sh
      env:
        CATALINA_HOME: "${{github.workspace}}/tomcat/"
        JMETER: "${{github.workspace}}/jmeter/bin/jmeter"
    - name: result
      run: bash bench/result.sh out

    - uses: actions/upload-artifact@v3
	  if: always()
      with: 
        name: logs
        path: |
          ${{github.workspace}}/tomcat/logs
          out
