name: benchmark

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8

    - name: build
      run: mvn -B package

    - name: install dependencies
      run: |
        sudo apt-get install siege
        wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.55/bin/apache-tomcat-9.0.55.tar.gz | tar xzf

    - name: run bench
      run: bash bench.sh
      env:
        CATALINA_HOME: apache-tomcat-9.0.55
