name: benchmark

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: graalvm/setup-graalvm@v1
      with:
        version: latest
        java-version: 11
        components: native-image
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: build
      run: mvn -B package
    - name: build native image 
      run: native-image --install-exit-handlers --static --no-fallback -jar unknow-http-test/target/server.jar server-native

    - uses: actions/upload-artifact@v3
      if: always()
      with: 
        name: server
        path: |
          unknow-http-test/target/server.jar 
          server-native
          unknow-http-test/target/*.war

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        t: ['tomcat', 'unknow', 'native']
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: server
    - uses: graalvm/setup-graalvm@v1
      with:
        version: latest
        java-version: 11
        components: native-image
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: prepare test
      run: bash bench/prepare.sh
    - name: run bench
      run: bash bench/run.sh ${{matrix.t}}
      env:
        CATALINA_HOME: "${{github.workspace}}/tomcat/"
        JMETER: "${{github.workspace}}/jmeter/bin/jmeter"
    - uses: actions/upload-artifact@v3
      if: always()
      with: 
        name: results-${{matrix.t}}
        path: out/*

  result:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: results-unknow
        path: out/
    - uses: actions/download-artifact@v3
      with:
        name: results-tomcat
        path: out/
    - uses: actions/download-artifact@v3
      with:
        name: results-native
        path: out/
    - name: result
      run: bash bench/result.sh out
