name: benchmark

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8

    - name: build
      run: mvn -B package

    - name: install dependencies
      run: sudo apt-get install siege tomcat9

    - name: test
      run: cat /etc/systemd/system/multi-user.target.wants/tomcat9.service

    - name: run bench
      run: bash .github/bench.sh
