name: test
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install
      run: |
        sudo apt install mailutils -y
        echo "${{ MAVEN_GPG_KEY }}" > file
    - uses: actions/upload-artifact@v7
      with:
        path: file
