name: validate

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [11, 17]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{matrix.version}}
        server-id: repsy
        server-username: MVN_USER
        server-password: MVN_PASS

    - name: build
      run: mvn -B package

    - name: install xmllint
      run: |-
          sudo apt update
          sudo apt install libxml2-utils
    - name: validate
      run: bash .github/validate.sh
