name: validate

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: ouzi-dev/commit-status-updater@v1.1.0
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8
        server-id: repsy
        server-username: MVN_USER
        server-password: MVN_PASS

    - name: build
      run: mvn -B package

    - name: install xmllint
      run: |-
          sudo apt update
          sudo apt install libxml2-utils
    - name: validate
      run: bash .github/validate.sh
    - uses: ouzi-dev/commit-status-updater@v1.1.0
      if: always()
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        status: "${{ job.status }}"
